In [1]:
#import library
import numpy as np
import pandas as pd


In [2]:
#load data
data = pd.read_csv('dataset_sms_spam _v1.csv')

In [3]:
data.head()

Teks  label
0  [PROMO] Beli paket Flash mulai 1GB di MY TELKO...      2
1  2.5 GB/30 hari hanya Rp 35 Ribu Spesial buat A...      2
2  2016-07-08 11:47:11.Plg Yth, sisa kuota Flash ...      2
3  2016-08-07 11:29:47.Plg Yth, sisa kuota Flash ...      2
4  4.5GB/30 hari hanya Rp 55 Ribu Spesial buat an...      2

In [4]:
data.label.value_counts()

0    569
1    335
2    239
Name: label, dtype: int64

In [5]:
#mengubah data text menjadi matriks
from sklearn.feature_extraction.text import CountVectorizer

vect = CountVectorizer()
vect.fit(data.Teks)
X = vect.transform(data.Teks)

In [6]:
X

<1143x4951 sparse matrix of type '<class 'numpy.int64'>'
	with 19191 stored elements in Compressed Sparse Row format>

In [7]:
#split train test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, data.label)

In [8]:
#train machine learning model
from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()
model.fit(X_train, y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [9]:
#lakukan prediksi
y_pred = model.predict(X_test)

In [10]:
#evaluasi model
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.metrics import classification_report

print("confusion matrix: ")
print(confusion_matrix(y_pred, y_test))
print("Accuracy score : ")
print(accuracy_score(y_pred, y_test))
print("classification report: ")
print(classification_report(y_pred,y_test))

confusion matrix: 
[[137   1   0]
 [  4  77   2]
 [  4   6  55]]
Accuracy score : 
0.9405594405594405
classification report: 
              precision    recall  f1-score   support

           0       0.94      0.99      0.97       138
           1       0.92      0.93      0.92        83
           2       0.96      0.85      0.90        65

    accuracy                           0.94       286
   macro avg       0.94      0.92      0.93       286
weighted avg       0.94      0.94      0.94       286



In [11]:
#masukan data baru
sms_baru = ["hay no sex no s@ra", 
            "masih kesepian hubungi akyu",
            "paham sex radikal pilih pemilu sudah dekat",
            "CC Kt@ judi bola hajar jahanam, KEJARI"]
    
# langkah 1: ubah dari teks jadi matriks
sms_baru_vec = vect.transform(sms_baru)

#langkah 2: masukkan ke dalam model machine learning
hasil  = model.predict(sms_baru_vec)

print(hasil)

[1 2 0 0]


In [12]:
#train model
# train machine learning model
from sklearn.naive_bayes import MultinomialNB
from sklearn.svm import LinearSVC

model = MultinomialNB(alpha=0.8)

model.fit(X_train, y_train)

model2 = LinearSVC()

model2.fit(X_train, y_train)

LinearSVC(C=1.0, class_weight=None, dual=True, fit_intercept=True,
          intercept_scaling=1, loss='squared_hinge', max_iter=1000,
          multi_class='ovr', penalty='l2', random_state=None, tol=0.0001,
          verbose=0)

In [13]:
y_pred2 = model2.predict(X_test)